1.0.6

diff --git a/cdib b/cdib
--- a/cdib
+++ b/cdib
@@ -1,11 +1,10 @@
 #!/bin/bash
 
-version=1.0.5
-mac=false
 tmp=~/.dcdib_tmp 
+os=$(uname)
 
 unmount_cd () {
-if [ "$mac" = true ]; then
+if [ "$os" = "Darwin" ]; then
     disktool -u disk1 0 > /dev/null 2>&1
 else
     umount /mnt/cdrom > /dev/null 2>&1
@@ -22,14 +21,12 @@ if [ ! -f "$1" ]; then
     exit 1
 fi
 
-
-if [ -e "/System/Library/CoreServices/SystemVersion.plist" ]; then
-	mac=true
+if [ "$os" = "Darwin" ]; then
 	cdrecord=/Applications/DCDIB.app/bin/cdrecord
 	cdirip=/Applications/DCDIB.app/bin/cdirip
 else
-	cdrecord=/usr/local/dreamcast-cdi-burner-$version-linux/bin/cdrecord
-	cdirip=/usr/local/dreamcast-cdi-burner-$version-linux/bin/cdirip
+	cdrecord=/usr/local/dreamcast-cdi-burner/bin/cdrecord
+	cdirip=/usr/local/dreamcast-cdi-burner/bin/cdirip
 fi
 
 if [[ $EUID -ne 0 ]]; then 
@@ -41,32 +38,32 @@ unmount_cd
 
 rm -rf $tmp
 mkdir $tmp
-echo "Extracting $cdi"
+echo "Extracting $cdi..."
 $cdirip "$1" $tmp 
 cd $tmp 
-echo "Looking For Burner Services, Please Wait"
 
-if [ "$mac" = true ]; then
+if [ "$os" = "Darwin" ]; then
+    echo "Looking For Burner Services, Please Wait"
 	if ioreg -l | grep "IOCompactDiscServices"; then
-	device=IOCompactDiscServices
+	    device=IOCompactDiscServices
 	elif ioreg -l | grep "IODVDServices"; then
-	device=IODVDServices
+	    device=IODVDServices
 	else
-	echo "Can Not Determine Burner, Nothing Burned"
-	rm -rf $tmp
-	exit 1
+	    echo "Can Not Determine Burner, Nothing Burned"
+	    rm -rf $tmp
+	    exit 1
 	fi
     echo "Found Service: $device"
 fi
 
-echo "Burning"
+echo "Burning..."
 if [ -f "taudio01.wav" ]; then
     echo "Detected CDI Type: WAV Track 1"
     for f in *wav; do echo -n " -audio $f" >> a; done
     b1=$(cat a)
     unmount_cd
     
-	if [ "$mac" = true ]; then
+	if [ "$os" = "Darwin"  ]; then
 	    $cdrecord -speed=8 -v dev=$device -dao -multi $b1
 	else
 	    $cdrecord -speed=8 -v -dao -multi $b1
@@ -74,7 +71,7 @@ if [ -f "taudio01.wav" ]; then
     
     unmount_cd
 
-	if [ "$mac" = true ]; then
+	if [ "$os" = "Darwin"  ]; then
 	    $cdrecord -overburn -speed=8 -v dev=$device -tao -xa *.iso
 	else
 	    $cdrecord -overburn -speed=8 -v -tao -xa *.iso
@@ -86,7 +83,7 @@ elif [ -f "tdata01.iso" ]; then
     echo "Detected CDI Type: ISO Track 1"
     unmount_cd
 
-	if [ "$mac" = true ]; then
+	if [ "$os" = "Darwin" ]; then
 	    $cdrecord -speed=8 -v dev=$device -tao -multi -xa tdata01.iso
 	else
 	    $cdrecord -speed=8 -v -tao -multi -xa tdata01.iso
@@ -94,17 +91,15 @@ elif [ -f "tdata01.iso" ]; then
 
     unmount_cd
 
-	if [ "$mac" = true ]; then	
+	if [ "$os" = "Darwin" ]; then	
 	    $cdrecord -overburn -speed=8 -v dev=$device -tao -multi -xa tdata02.iso
 	else
 	    $cdrecord -overburn -speed=8 -v -tao -multi -xa tdata02.iso
 	fi
 
     unmount_cd
-
 else
-
-    echo "Failed To Find Burn Files, Nothing Burned"
+    echo "Failed To Find Burn Files, Nothing Burned!"
     rm -rf $tmp
     exit 1
 
@@ -113,20 +108,20 @@ fi
 rm -rf $tmp
 unmount_cd
 
-if [ "$mac" = true ]; then
-
+if [ "$os" = "Darwin" ]; then
 	if [ -f "/usr/bin/drutil" ]; then
-	    echo "Ejecting CD-ROM"
+	    echo "Ejecting CD-ROM, please wait..."
 	    drutil eject cd
 	fi
 	
 	if [ -f "/usr/bin/afplay" ]; then
-
 		if [ -f "/System/Library/Sounds/Glass.aiff" ]; then
 		    afplay /System/Library/Sounds/Glass.aiff
 		fi
-
 	fi
-
+else
+	    echo "Ejecting CD-ROM, please wait..."
+        eject
 fi
+
 echo "Complete!"
